name: psa-carga-horas
services:
  backend:
    build:
      context: ./backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - PORT=${BACKEND_PORT}
      - DATABASE_HOST=base-de-datos
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_DB=${DATABASE_DB}
    depends_on:
      base-de-datos:
        condition: service_healthy

  base-de-datos:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_DB}
    ports:
      - "${DATABASE_PORT}:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DATABASE_USER} -d ${DATABASE_DB} -h localhost",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
