name: psa-carga-horas
services:
  base-de-datos:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: psa_db
    ports:
      - "${DATABASE_PORT:-5432}:5432"
