name: Generación de reportes de test del backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  generar-reportes:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '8.10'

    - name: Build with Gradle Wrapper
      run: |
        cd backend
        chmod 777 ./gradlew
        chmod +x ./gradlew
        ./gradlew dependencies
        ./gradlew build

    - name: Run Unit Tests and Generate Reports
      run: |
        cd backend
        ./gradlew test

    - name: Run Cucumber Tests and Generate Reports
      run: |
        cd backend
        ./gradlew cucumberTest

    - name: Archive Test Reports
      uses: actions/upload-artifact@v3
      with:
        name: test-reports
        path: |
          backend/app/build/reports/tests/test/index.html
          backend/app/build/reports/cucumber/test/index.html
